### ISSUE TITLE
Opencv error

### ISSUE THREAD

**Issue by BenMuhit** [ntnbrtnkv/chess-recognize#1]
hello
when i copy examples/5.png to clipboard and run source in vscode or run Chess.Recognize.exe i got this error: 
OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1164: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'

thank advance for your reply.

**Comment by ntnbrtnkv** [comment]
Hi, try to use `Shift+Win+S` for capturing chess board

**Comment by BenMuhit** [comment]
I copied it to clipboard via your advice or image  
module clipboard func or paint and  I got this error. When I debug it CV.readimage got an array with three element, no channel , but your program running 5.png when reading directly, got four element, with a channel . How can it be?

**Comment by BenMuhit** [comment]
solved :
            img = ImageGrab.grabclipboard()
            img.save('clipboard_image.png', 'PNG')  
            image = Image.open('clipboard_image.png').convert('RGBA')
            image.save('clipboard_image.png')
            res = self.recognize('clipboard_image.png')
